import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import HomeHero from "../components/HomeHero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rox Auto Parts - Taiwan Automotive Parts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center justify-center ">
        <HomeHero />
      </div>
    </>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale)),
      // Will be passed to the page component as props
    },
  };
}
